POST http://localhost:2525/imposters
content-Type: application/json
 
{
    "port": 4503,
    "protocol": "http",
    "name": "Exercicio3",
    "stubs": [{
        "responses": [
            {
               "is": {
                  "statusCode": 200,
                  "headers": { "Content-Type": "application/json" },
                  "body": {
                     "brand": "Toyota",
                     "details": {
                        "id": 1,
                        "model": "Super",
                        "Price": 400
                     }
                  }
               }
            }
         ],
         "predicates": [
            {
               "equals": {
                  "path": "/api/cars",
                  "method": "GET",
                  "query": {
                    "brand": "Toyota"
                    }
               }
            },
            {
               "not": {
                  "contains": { "body": "requiredField" },
                  "caseSensitive": true
               }
            }
         ]
      },
      {
         "responses": [
            {
               "is": {
                  "statusCode": 400,
                  "headers": { "Content-Type": "application/json" },
                  "body": {
                     "details": "NULL"
                  }
               }
            }
         ],
         "predicates": [
            {
               "equals": {
                  "path": "/api/cars",
                  "method": "GET"
               }
            },
            {
               "not": {
                  "contains": { "body": "requiredField" },
                  "caseSensitive": true
               }
            }
         ]
      }
   ]
}
 
###
GET http://localhost:4553/api/cars?brand=Toyota
Content-Type: application/json
 
{"optionalField": true}
 
###
GET http://localhost:4553/api/cars?cars=BMW
Content-Type: application/json
 
{"optionalField": true}