POST http://localhost:2525/imposters
content-Type: application/json

{
   "port":4505,
   "protocol":"http",
   "name":"Exercicio5",
   "stubs": [
  {
    "responses": [
      {
        "is": {
          "statusCode": 200,
          "headers": { "Content-Type": "application/json" },
          "body": { 
            "status": "Ok", 
            "token": "validtoken" 
            }
        }
      }
    ],
    "predicates": [
      {
        "deepEquals": {
          "path": "/api/login",
          "method": "POST",
          "body": { 
            "username": "admin", 
            "password": "secret" 
            }
        }
      }
    ]
  },
  {
    "responses": [
      {
        "is": {
          "statusCode": 401,
          "headers": { "Content-Type": "application/json" },
          "body": { 
            "status": "Incorrect", 
            "token": "InvalidToken" 
            }
        }
      }
    ],
    "predicates": [
      {
        "deepEquals": {
          "path": "/api/login",
          "method": "POST",
          "body": { 
            "username": "notAdmin", 
            "password": "Public" 
            }
        }
      }
    ]
  }
]
}



###
POST http://localhost:4555/api/login
Content-Type: application/json

{ 
  "username": "admin", 
  "password": "secret"
}

###
POST http://localhost:4555/api/login
Content-Type: application/json

{ 
  "username": "notAdmin", 
  "password": "Public"
}